"""empty message

Revision ID: 2c496494d0ce
Revises: a64bf64dbdfc
Create Date: 2021-10-22 03:58:55.316714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c496494d0ce'
down_revision = 'a64bf64dbdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('img_src', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'img_src')
    # ### end Alembic commands ###
