"""empty message

Revision ID: 3062fb999dd0
Revises: 99e4e731f8d7
Create Date: 2021-10-21 18:19:33.542337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3062fb999dd0'
down_revision = '99e4e731f8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('taskers_category_id_fkey', 'taskers', type_='foreignkey')
    op.drop_column('taskers', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskers', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('taskers_category_id_fkey', 'taskers', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
