"""empty message

Revision ID: 879e4791569b
Revises: 2c496494d0ce
Create Date: 2021-10-24 14:41:07.914044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879e4791569b'
down_revision = '2c496494d0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskers', sa.Column('bio', sa.Text(), nullable=False))
    op.add_column('taskers', sa.Column('profile_pic', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskers', 'profile_pic')
    op.drop_column('taskers', 'bio')
    # ### end Alembic commands ###
