"""empty message

Revision ID: 8958c331376a
Revises: f3decd45e8b4
Create Date: 2021-10-25 01:55:17.602165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8958c331376a'
down_revision = 'f3decd45e8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'duration',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
