"""empty message

Revision ID: a64bf64dbdfc
Revises: 2d3bc3823965
Create Date: 2021-10-21 19:37:29.147409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64bf64dbdfc'
down_revision = '2d3bc3823965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskers_to_categories', 'tasker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('taskers_to_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('taskers_to_categories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskers_to_categories', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('taskers_to_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('taskers_to_categories', 'tasker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
