"""empty message

Revision ID: cb2393035724
Revises: 7ec9bb218eea
Create Date: 2021-10-28 05:42:43.316598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2393035724'
down_revision = '7ec9bb218eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'content',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'content',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
