"""empty message

Revision ID: f3decd45e8b4
Revises: 879e4791569b
Create Date: 2021-10-24 22:05:13.846392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3decd45e8b4'
down_revision = '879e4791569b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('details', sa.Text(), nullable=False))
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'details')
    op.drop_column('orders', 'duration')
    # ### end Alembic commands ###
